# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Eunyoung Bang | Personal website
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
# baseurl: "/eunyoung" # the subpath of the site
url: "https://yeong35.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: HOME
      slug: /
    - name: WORK
    # - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: eyeong1126@gmail.com
      link: eyeong1126@gmail.com
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  follow:
    # - name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    # - name: Facebook
    #   link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: https://linkedin.com/in/eunyoung-bang-3a312b238/
    - name: GitHub
      link: https://github.com/yeong35
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    # - name: RSS
    #   link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
